### ISSUE TITLE
Sub operator

### ISSUE THREAD

**Issue by Xydez** [olliemath/chronoutil#9]
Hello!

Is there any good reason why the Add operator is implemented but not the Sub operator? For RelativeDuration and Datelike

**Comment by olliemath** [comment]
Hey,

so no actually. It's only really missing as I tend to _add negative durations_ rather than subtract a positive one in my code (e.g. you can do `my_date + (-my_duration)`)

Happy to implement this though

**Comment by olliemath** [comment]
See 0.2.5 release
